default_language_version:
  python: python3

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix", "--config=ruff.toml"]
      - id: ruff-format
        args: ["--config=ruff.toml"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-setuptools]
        args: ["--cache-dir=.mypy_cache", "--config-file=mypy.ini"]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: yamllint (workflows)
        files: ^\.github/workflows/.*\.(yml|yaml)$
        args: ["-c", ".yamllint"]
