name: Budget Alerts

on:
  schedule:
    - cron: "0 7 * * *"  # elke dag 07:00 UTC
  workflow_dispatch:

permissions: read-all

jobs:
  budget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run budget check
        run: |
          echo "No budget script yet"
