name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install fastapi pydantic openai numpy ruff
      - name: Lint with ruff
        run: |
          ruff .
      - name: Run all tests
        run: |
          python run_tests.py
      - name: Report failures to self_improving_agent (optional)
        if: failure()
        run: |
          echo "Tests failed. Reporting to self_improving_agent..."
          # Add your reporting logic here (e.g. curl, python script)
