name: Ruff & Mypy

on:
  pull_request:
  push:
    branches: ["**"]

jobs:
  lint-type:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip & mypy
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .mypy_cache
          key: ${{ runner.os }}-py311-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') }}

      - name: Install tooling
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Ruff (format check + lint)
        run: |
          ruff check .
          ruff format --check .

      - name: Mypy (type checking)
        run: |
          mypy . --config-file mypy.ini
          mypy --show-config --config-file mypy.ini
