name: Secrets & Variables Check

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if OPENAI_API_KEY missing
        if: ${{ secrets.OPENAI_API_KEY == '' }}
        run: |
          echo "❌ Missing required secret: OPENAI_API_KEY"
          exit 1

      - name: Finance checks (only when REQUIRE_FINANCE=true)
        if: ${{ vars.REQUIRE_FINANCE == 'true' }}
        shell: bash
        run: |
          set -e
          [ -n "${{ secrets.GOOGLE_SHEETS_TOKEN }}" ] || { echo "❌ Missing GOOGLE_SHEETS_TOKEN"; exit 1; }
          [ -n "${{ secrets.GOOGLE_SHEETS_ID }}" ]    || { echo "❌ Missing GOOGLE_SHEETS_ID"; exit 1; }
          [ -n "${{ secrets.NOTION_API_KEY }}" ]      || { echo "❌ Missing NOTION_API_KEY"; exit 1; }
          [ -n "${{ secrets.NOTION_DATABASE_ID }}" ]  || { echo "❌ Missing NOTION_DATABASE_ID"; exit 1; }
          echo "✅ Finance secrets present."
