name: Daily Finance Sync

on:
  schedule:
    - cron: "0 4 * * *"  # daily at 04:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SHEETS_TOKEN: ${{ secrets.GOOGLE_SHEETS_TOKEN }}
      GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Sync to Google Sheets
        run: |
          python finance/google_sheets_sync.py --sheet "$GOOGLE_SHEETS_ID"
      - name: Sync to Notion
        run: |
          python finance/notion_sync.py --token "$NOTION_API_KEY" --db "$NOTION_DATABASE_ID"
